-- D1 schema. Committed: this is structure, not data.
-- The seed (0002_seed.sql) is GENERATED and GITIGNORED -- a committed seed is
-- a data file wearing a costume, and hard rule 1 says no data in the repo.

PRAGMA foreign_keys = ON;

-- Reproducibility anchor. Every published artifact pins the snapshot it was
-- built from, so an analysis can be regenerated byte-for-byte and audited.
CREATE TABLE IF NOT EXISTS snapshots (
  snapshot_id   TEXT PRIMARY KEY,
  created_at    TEXT NOT NULL,
  sources_json  TEXT NOT NULL,   -- {source_id: sha256 of that source's raw payload}
  row_counts    TEXT NOT NULL    -- {table: count}, for the data-quality gate
);

CREATE TABLE IF NOT EXISTS players (
  player_id     TEXT PRIMARY KEY,   -- normalized: "fpl:<element_id>:<season>"
  fpl_element   INTEGER NOT NULL,
  season        TEXT NOT NULL,
  web_name      TEXT NOT NULL,
  first_name    TEXT NOT NULL,
  second_name   TEXT NOT NULL,
  position      TEXT NOT NULL,      -- controlled code; labels live in the catalog
  team          TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_players_season ON players(season);
CREATE INDEX IF NOT EXISTS idx_players_web_name ON players(web_name);

CREATE TABLE IF NOT EXISTS player_season_stats (
  player_id     TEXT NOT NULL,
  season        TEXT NOT NULL,
  competition   TEXT NOT NULL DEFAULT 'PL',
  goals         INTEGER NOT NULL DEFAULT 0,
  assists       INTEGER NOT NULL DEFAULT 0,
  minutes       INTEGER NOT NULL DEFAULT 0,
  points        INTEGER NOT NULL DEFAULT 0,
  xg            REAL,
  snapshot_id   TEXT NOT NULL,
  PRIMARY KEY (player_id, season, competition),
  FOREIGN KEY (player_id) REFERENCES players(player_id)
);

CREATE INDEX IF NOT EXISTS idx_pss_season ON player_season_stats(season, competition);

-- Season-level results, from the public-domain / PDDL match feeds.
CREATE TABLE IF NOT EXISTS season_stats (
  season        TEXT NOT NULL,
  competition   TEXT NOT NULL DEFAULT 'PL',
  played        INTEGER NOT NULL,
  won           INTEGER NOT NULL,
  drawn         INTEGER NOT NULL,
  lost          INTEGER NOT NULL,
  goals         INTEGER NOT NULL,
  goals_against INTEGER NOT NULL,
  snapshot_id   TEXT NOT NULL,
  PRIMARY KEY (season, competition)
);

-- Asset registry: the Dagster-style staleness check. "Does a row exist with
-- matching versions?" Absent or differing -> stale -> materialize.
CREATE TABLE IF NOT EXISTS assets (
  asset_key         TEXT PRIMARY KEY,   -- sha256 over the version 4-tuple
  intent_json       TEXT NOT NULL,
  snapshot_id       TEXT NOT NULL,
  transform_version TEXT NOT NULL,
  renderer_version  TEXT NOT NULL,
  status            TEXT NOT NULL,      -- 'ready' | 'pending' | 'failed'
  r2_path           TEXT,
  created_at        TEXT NOT NULL
);

-- Demand signal. Infeasible requests are the MOST valuable rows here: they say
-- what data to integrate next. Intent hash only -- no PII, no accounts.
CREATE TABLE IF NOT EXISTS demand_log (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  intent_hash   TEXT NOT NULL,
  metric        TEXT NOT NULL,
  season        TEXT NOT NULL,
  viz           TEXT NOT NULL,
  state         TEXT NOT NULL,          -- the feasibility state returned
  created_at    TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_demand_state ON demand_log(state, created_at);

-- Budget breaker for the compute path (/api/query, /ask, /q). One row per UTC
-- day -- the day boundary IS the reset, no separate cleanup job needed. D1 is
-- the authoritative counter (atomic upsert, strongly consistent); the KV read
-- in front of it is a cheap pre-filter, not the source of truth, because KV
-- writes are eventually consistent and have no atomic increment.
CREATE TABLE IF NOT EXISTS budget_counter (
  day    TEXT PRIMARY KEY,   -- UTC date, YYYY-MM-DD
  count  INTEGER NOT NULL DEFAULT 0
);
