-- D1 schema. Committed: this is structure, not data.
-- The seed (0002_seed.sql) is GENERATED and GITIGNORED -- a committed seed is
-- a data file wearing a costume, and hard rule 1 says no data in the repo.

PRAGMA foreign_keys = ON;

-- Reproducibility anchor. Every published artifact pins the snapshot it was
-- built from, so an analysis can be regenerated byte-for-byte and audited.
CREATE TABLE IF NOT EXISTS snapshots (
  snapshot_id   TEXT PRIMARY KEY,
  created_at    TEXT NOT NULL,
  sources_json  TEXT NOT NULL,   -- {source_id: sha256 of that source's raw payload}
  row_counts    TEXT NOT NULL    -- {table: count}, for the data-quality gate
);

CREATE TABLE IF NOT EXISTS players (
  player_id     TEXT PRIMARY KEY,   -- normalized: "fpl:<element_id>:<season>"
  fpl_element   INTEGER NOT NULL,
  season        TEXT NOT NULL,
  web_name      TEXT NOT NULL,
  first_name    TEXT NOT NULL,
  second_name   TEXT NOT NULL,
  position      TEXT NOT NULL,      -- controlled code; labels live in the catalog
  team          TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_players_season ON players(season);
CREATE INDEX IF NOT EXISTS idx_players_web_name ON players(web_name);

-- Stable source identity across seasons. Keep players.player_id season-scoped:
-- FPL element ids change between seasons and remain the correct fact key.
-- This additive mapping makes mixed-version deploys and rollback safe: an old
-- Worker ignores it, while the new Worker never falls back to name joining.
CREATE TABLE IF NOT EXISTS player_identities (
  player_id          TEXT PRIMARY KEY,
  person_id          TEXT NOT NULL, -- source-namespaced: "fpl:code:<code>"
  source_id          TEXT NOT NULL CHECK (source_id = 'fpl'),
  source_person_code INTEGER NOT NULL CHECK (source_person_code > 0),
  season             TEXT NOT NULL,
  FOREIGN KEY (player_id) REFERENCES players(player_id) ON DELETE CASCADE,
  UNIQUE (person_id, season),
  UNIQUE (source_id, source_person_code, season)
);

CREATE INDEX IF NOT EXISTS idx_player_identities_person
  ON player_identities(person_id);

CREATE TABLE IF NOT EXISTS player_season_stats (
  player_id     TEXT NOT NULL,
  season        TEXT NOT NULL,
  competition   TEXT NOT NULL DEFAULT 'PL',
  goals         INTEGER NOT NULL DEFAULT 0,
  assists       INTEGER NOT NULL DEFAULT 0,
  minutes       INTEGER NOT NULL DEFAULT 0,
  points        INTEGER NOT NULL DEFAULT 0,
  xg            REAL,
  snapshot_id   TEXT NOT NULL,
  PRIMARY KEY (player_id, season, competition),
  FOREIGN KEY (player_id) REFERENCES players(player_id)
);

CREATE INDEX IF NOT EXISTS idx_pss_season ON player_season_stats(season, competition);

-- Season-level results, from the public-domain / PDDL match feeds.
CREATE TABLE IF NOT EXISTS season_stats (
  season        TEXT NOT NULL,
  competition   TEXT NOT NULL DEFAULT 'PL',
  played        INTEGER NOT NULL,
  won           INTEGER NOT NULL,
  drawn         INTEGER NOT NULL,
  lost          INTEGER NOT NULL,
  goals         INTEGER NOT NULL,
  goals_against INTEGER NOT NULL,
  snapshot_id   TEXT NOT NULL,
  PRIMARY KEY (season, competition)
);

-- Asset registry: the Dagster-style staleness check. "Does a row exist with
-- matching versions?" Absent or differing -> stale -> materialize.
CREATE TABLE IF NOT EXISTS assets (
  asset_key         TEXT PRIMARY KEY,   -- sha256 over the version 4-tuple
  intent_json       TEXT NOT NULL,
  snapshot_id       TEXT NOT NULL,
  transform_version TEXT NOT NULL,
  renderer_version  TEXT NOT NULL,
  status            TEXT NOT NULL,      -- 'ready' | 'pending' | 'failed'
  r2_path           TEXT,
  created_at        TEXT NOT NULL
);

-- Retire the original event-level demand log. Its exact hash/season/timestamp
-- tuples were enumerable and linkable to Access/provider timing. Old Workers
-- already treat logging failure as non-fatal, so dropping it is rollback-safe.
DROP TABLE IF EXISTS demand_log;

-- Content-addressed query results. The artifact key already binds the
-- canonical intent, snapshot and code/renderer versions; snapshot_id is kept
-- in the primary key as an explicit stale-result guard. This table contains
-- results only, never natural-language questions or requester information.
CREATE TABLE IF NOT EXISTS query_result_cache (
  artifact_key  TEXT NOT NULL CHECK (length(artifact_key) = 64 AND artifact_key NOT GLOB '*[^0-9a-f]*'),
  snapshot_id   TEXT NOT NULL CHECK (length(snapshot_id) = 64 AND snapshot_id NOT GLOB '*[^0-9a-f]*'),
  schema_version INTEGER NOT NULL DEFAULT 1 CHECK (schema_version = 1),
  result_json   TEXT NOT NULL CHECK (length(result_json) BETWEEN 1 AND 100000),
  PRIMARY KEY (artifact_key, snapshot_id)
) WITHOUT ROWID;

-- Privacy-safe demand telemetry. These are lifetime counters over finite,
-- code-owned dimensions, not request events. Deliberately absent: timestamps,
-- artifact/intent hashes, seasons, entity ids, questions, identities, network
-- data, headers and free-form errors. The fingerprintable legacy event table
-- above is removed; old Workers already fail open when that write is absent.
CREATE TABLE IF NOT EXISTS query_demand_aggregate (
  metric            TEXT NOT NULL CHECK (metric IN ('goals', 'assists', 'minutes', 'points', 'xg', 'progressive_passes', 'other')),
  question_family   TEXT NOT NULL CHECK (question_family IN ('player_ranking', 'player_lookup', 'team_season', 'match', 'opponent', 'competition')),
  viz               TEXT NOT NULL CHECK (viz IN ('table', 'bar', 'dot_plot', 'line', 'shot_map', 'pass_map', 'heatmap')),
  feasibility_state TEXT NOT NULL CHECK (feasibility_state IN ('available', 'computable_now_queued', 'computable_but_expensive', 'no_data', 'no_rights')),
  cache_outcome     TEXT NOT NULL CHECK (cache_outcome IN ('hit', 'miss', 'unavailable', 'not_applicable')),
  result_outcome    TEXT NOT NULL CHECK (result_outcome IN ('success', 'refused', 'budget_exceeded')),
  locale            TEXT NOT NULL CHECK (locale IN ('api', 'en', 'es')),
  route_family      TEXT NOT NULL CHECK (route_family IN ('query_api', 'query_page', 'ask_page')),
  request_count     INTEGER NOT NULL DEFAULT 0 CHECK (request_count >= 0),
  PRIMARY KEY (metric, question_family, viz, feasibility_state, cache_outcome, result_outcome, locale, route_family)
) WITHOUT ROWID;

-- Budget breaker for the compute path (/api/query, /ask, /q). One row per UTC
-- day -- the day boundary IS the reset, no separate cleanup job needed. D1 is
-- the authoritative counter (atomic upsert, strongly consistent); the KV read
-- in front of it is a cheap pre-filter, not the source of truth, because KV
-- writes are eventually consistent and have no atomic increment.
CREATE TABLE IF NOT EXISTS budget_counter (
  day    TEXT PRIMARY KEY,   -- UTC date, YYYY-MM-DD
  count  INTEGER NOT NULL DEFAULT 0
);

-- One append-only record for each seed import that reached its final statement.
-- This is load metadata, not a claim that the subsequent Worker deploy succeeded.
CREATE TABLE IF NOT EXISTS publication_runs (
  run_id             INTEGER PRIMARY KEY AUTOINCREMENT,
  snapshot_id        TEXT NOT NULL,
  prepared_at        TEXT NOT NULL,
  source_status_json TEXT NOT NULL,
  loaded_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE INDEX IF NOT EXISTS idx_publication_runs_loaded
  ON publication_runs(loaded_at DESC, run_id DESC);
